import { z } from "zod";
import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { ok, fail } from "@/lib/api/response";
import { type ApiContext, register } from "@/lib/api/router";
import { generateMonthlyBill, getAllBills, getAllPayments, getMyBills, getMyPayments, submitPayment, verifyPayment } from "@/features/billing/queries";

async function billsHandler() {
  try {
    return ok({ bills: await getMyBills() });
  } catch (e) {
    return fail("FORBIDDEN", (e as Error).message);
  }
}

async function paymentsHandler() {
  try {
    return ok({ payments: await getMyPayments() });
  } catch (e) {
    return fail("FORBIDDEN", (e as Error).message);
  }
}

async function invoiceHandler(ctx: ApiContext) {
  try {
    const bill = (await getMyBills()).find((item) => item.id === ctx.params.id);
    if (!bill) return fail("NOT_FOUND", "Invoice not found.");
    const pdf = await PDFDocument.create();
    const page = pdf.addPage([595.28, 841.89]);
    const regular = await pdf.embedFont(StandardFonts.Helvetica);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
    const ink = rgb(0.08, 0.14, 0.12);
    const forest = rgb(0.04, 0.32, 0.23);
    page.drawRectangle({ x: 0, y: 750, width: 595.28, height: 91.89, color: ink });
    page.drawText("VERTICA RESIDENCES", { x: 46, y: 800, size: 18, font: bold, color: rgb(0.94, 0.9, 0.76) });
    page.drawText("BILLING STATEMENT", { x: 46, y: 776, size: 10, font: regular, color: rgb(0.82, 0.86, 0.84) });
    const money = (value: number) => `PHP ${value.toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    const info: Array<[string, string]> = [["Statement ID", bill.id], ["Billing period", `${bill.periodStart} to ${bill.periodEnd}`], ["Due date", bill.dueDate ?? "Not set"], ["Status", bill.status]];
    let y = 710;
    for (const [label, value] of info) { page.drawText(label, { x: 46, y, size: 9, font: bold, color: forest }); page.drawText(String(value), { x: 160, y, size: 9, font: regular, color: ink }); y -= 20; }
    y -= 18;
    page.drawRectangle({ x: 46, y: y - 8, width: 503, height: 28, color: rgb(0.93, 0.95, 0.94) });
    page.drawText("DESCRIPTION", { x: 58, y, size: 9, font: bold, color: ink });
    page.drawText("AMOUNT", { x: 460, y, size: 9, font: bold, color: ink });
    y -= 32;
    for (const item of bill.items) { page.drawText(item.description.slice(0, 58), { x: 58, y, size: 9, font: regular, color: ink }); page.drawText(money(item.amount), { x: 430, y, size: 9, font: regular, color: ink }); y -= 22; }
    y -= 10;
    const totals = [["Total", bill.totalAmount], ["Paid", bill.paidAmount], ["Balance due", bill.balance]] as const;
    for (const [label, value] of totals) { page.drawText(label, { x: 350, y, size: label === "Balance due" ? 11 : 9, font: bold, color: label === "Balance due" ? forest : ink }); page.drawText(money(value), { x: 430, y, size: label === "Balance due" ? 11 : 9, font: bold, color: label === "Balance due" ? forest : ink }); y -= 22; }
    page.drawText("Generated by Vertica, a fictional school-project property management demonstration.", { x: 46, y: 46, size: 8, font: regular, color: rgb(0.38, 0.42, 0.4) });
    const bytes = await pdf.save();
    return new NextResponse(Buffer.from(bytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="vertica-invoice-${bill.periodStart}.pdf"`,
        "Cache-Control": "private, no-store",
      },
    });
  } catch (error) {
    return fail("FORBIDDEN", (error as Error).message);
  }
}

async function allBillsHandler() {
  try {
    return ok({ bills: await getAllBills() });
  } catch (e) {
    return fail("FORBIDDEN", (e as Error).message);
  }
}

async function allPaymentsHandler() {
  try {
    return ok({ payments: await getAllPayments() });
  } catch (e) {
    return fail("FORBIDDEN", (e as Error).message);
  }
}

const generateBillSchema = z.object({
  leaseId: z.string().uuid(),
  periodStart: z.iso.date(),
  periodEnd: z.iso.date(),
  dueDate: z.iso.date(),
});

async function generateBillHandler(ctx: ApiContext) {
  let body: unknown;
  try { body = await ctx.req.json(); } catch { return fail("BAD_REQUEST", "Invalid JSON body."); }
  const parsed = generateBillSchema.safeParse(body);
  if (!parsed.success) return fail("BAD_REQUEST", "Complete the billing period and due date.", { issues: parsed.error.issues });
  try { return ok(await generateMonthlyBill(parsed.data)); }
  catch (error) { return fail("UNPROCESSABLE", (error as Error).message); }
}

const submitSchema = z.object({
  billId: z.string().uuid(),
  amount: z.number().positive().max(100_000_000),
  method: z.enum(["BANK_TRANSFER", "GCASH", "PAYMAYA", "CARD", "OVER_THE_COUNTER", "OTHER"]),
  externalReference: z.string().max(200).optional(),
});

async function submitPaymentHandler(ctx: ApiContext) {
  let body: unknown;
  try {
    body = await ctx.req.json();
  } catch {
    return fail("BAD_REQUEST", "Invalid JSON body.");
  }
  const parsed = submitSchema.safeParse(body);
  if (!parsed.success) return fail("BAD_REQUEST", "Invalid payment.", { issues: parsed.error.issues });
  try {
    const result = await submitPayment(parsed.data);
    return ok(result);
  } catch (e) {
    return fail("FORBIDDEN", (e as Error).message);
  }
}

const verifySchema = z.object({
  decision: z.enum(["APPROVED", "PARTIALLY_APPROVED", "REJECTED"]),
  approvedAmount: z.number().positive().max(100_000_000).optional(),
  reason: z.string().trim().min(1).max(2000).optional(),
}).superRefine((value, ctx) => {
  if (value.decision === "REJECTED" && !value.reason) {
    ctx.addIssue({ code: "custom", path: ["reason"], message: "A rejection reason is required." });
  }
  if (value.decision === "PARTIALLY_APPROVED" && (!value.reason || value.approvedAmount === undefined)) {
    ctx.addIssue({ code: "custom", path: ["reason"], message: "A partial approval amount and reason are required." });
  }
  if (value.decision === "APPROVED" && value.approvedAmount === undefined) {
    ctx.addIssue({ code: "custom", path: ["approvedAmount"], message: "An approved amount is required." });
  }
});

async function verifyPaymentHandler(ctx: ApiContext) {
  const paymentId = ctx.params?.id;
  if (!paymentId) return fail("BAD_REQUEST", "Missing payment id.");
  let body: unknown;
  try {
    body = await ctx.req.json();
  } catch {
    return fail("BAD_REQUEST", "Invalid JSON body.");
  }
  const parsed = verifySchema.safeParse(body);
  if (!parsed.success) return fail("BAD_REQUEST", "Invalid review decision.", { issues: parsed.error.issues });
  try {
    return ok(await verifyPayment({ paymentId, ...parsed.data }));
  } catch (e) {
    return fail("FORBIDDEN", (e as Error).message);
  }
}

export function registerBillingRoutes(): void {
  register("GET", "billing/me/bills", billsHandler);
  register("GET", "billing/me/bills/:id/invoice", invoiceHandler);
  register("GET", "billing/me/payments", paymentsHandler);
  register("POST", "billing/me/payments", submitPaymentHandler);
  register("GET", "billing/all/bills", allBillsHandler);
  register("GET", "billing/all/payments", allPaymentsHandler);
  register("POST", "billing/bills", generateBillHandler);
  register("POST", "billing/payments/:id/verify", verifyPaymentHandler);
}
