/**
 * Generates docs/database/data-dictionary.md by parsing the CREATE TABLE
 * statements in supabase/migrations. Runs without a database connection.
 *
 * Usage: npm run docs:dd
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, join } from "node:path";

interface TableDef {
  name: string;
  columns: string[];
  migration: string;
}

function parseTables(sql: string, migration: string): TableDef[] {
  const tables: TableDef[] = [];
  const re = /create table if not exists public\.(\w+)\s*\(([\s\S]*?)\n\);/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(sql)) !== null) {
    const name = m[1]!;
    const body = m[2]!;
    const columns: string[] = [];
    for (const rawLine of body.split("\n")) {
      const line = rawLine.trim().replace(/,$/, "");
      if (!line) continue;
      const lower = line.toLowerCase();
      if (
        lower.startsWith("constraint") ||
        lower.startsWith("unique") ||
        lower.startsWith("primary key") ||
        lower.startsWith("check") ||
        lower.startsWith("foreign key") ||
        lower.startsWith("--")
      ) {
        continue;
      }
      const colName = line.split(/\s+/)[0];
      if (colName && /^[a-z_]+$/.test(colName)) columns.push(colName);
    }
    tables.push({ name, columns, migration });
  }
  return tables;
}

function main() {
  const dir = resolve(process.cwd(), "supabase", "migrations");
  if (!existsSync(dir)) {
    console.error("No migrations directory.");
    process.exit(1);
  }
  const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
  const all: TableDef[] = [];
  for (const f of files) {
    const sql = readFileSync(join(dir, f), "utf8");
    all.push(...parseTables(sql, f));
  }

  const lines: string[] = [
    "# Data dictionary",
    "",
    "> Generated by `npm run docs:dd` from `supabase/migrations`. Do not edit by hand.",
    "",
    `Total tables: **${all.length}**`,
    "",
  ];
  for (const t of all) {
    lines.push(`## \`${t.name}\``, "", `_Defined in: ${t.migration}_`, "", "| Column |", "| --- |");
    for (const c of t.columns) lines.push(`| \`${c}\` |`);
    lines.push("");
  }

  const outDir = resolve(process.cwd(), "docs", "database");
  mkdirSync(outDir, { recursive: true });
  const outFile = join(outDir, "data-dictionary.md");
  writeFileSync(outFile, lines.join("\n"), "utf8");
  console.log(`[data-dictionary] Wrote ${all.length} tables to ${outFile}`);
}

main();
