"use client";

import { useCallback, useEffect, useState } from "react";
import { formatPeso } from "@/lib/utils/format";
import { useRealtimeTables } from "@/components/realtime/RealtimeRefresh";

type Payment = { id: string; billId: string | null; submittedAmount: number; method: string; status: string; submittedAt: string };
type Decision = "APPROVED" | "PARTIALLY_APPROVED" | "REJECTED";

export default function AdminPaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]); const [state, setState] = useState("loading"); const [active, setActive] = useState<Payment | null>(null); const [decision, setDecision] = useState<Decision>("APPROVED"); const [approvedAmount, setApprovedAmount] = useState(""); const [reason, setReason] = useState(""); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/v1/billing/all/payments", { cache: "no-store" }); const json = await response.json(); if (!json.ok) throw new Error(); setPayments(json.data.payments ?? []); setState("ready"); } catch { setState("error"); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useRealtimeTables(["payments"], load);
  function begin(payment: Payment) { setActive(payment); setDecision("APPROVED"); setApprovedAmount(String(payment.submittedAmount)); setReason(""); setMessage(null); }
  async function review() { if (!active) return; setSaving(true); setMessage(null); const body: Record<string, unknown> = { decision }; if (decision !== "REJECTED") body.approvedAmount = Number(approvedAmount); if (decision !== "APPROVED") body.reason = reason; try { const response = await fetch(`/api/v1/billing/payments/${active.id}/verify`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); if (!json.ok) { setMessage(json.error?.message ?? "Payment review could not be saved."); return; } setPayments((current) => current.map((payment) => payment.id === active.id ? { ...payment, status: json.data.status } : payment)); setActive(null); } catch { setMessage("Network error. Your review was not saved."); } finally { setSaving(false); } }
  return <div className="page-shell"><header className="page-header"><p className="eyebrow">Payment control</p><h1>Review payment submissions</h1><p>Approve, partially approve, or reject each submitted payment. A decision updates the payment and its bill together.</p></header>
    {state === "loading" && <p className="text-sm text-neutral-500" role="status">Loading payment submissions…</p>}{state === "error" && <div className="empty-state" role="alert">Payments could not be loaded.</div>}{state === "ready" && payments.length === 0 && <div className="empty-state">No payment submissions have been recorded.</div>}
    {state === "ready" && payments.length > 0 && <div className="surface-card overflow-hidden"><table className="data-table data-table--responsive"><thead><tr><th>Submitted</th><th>Method</th><th>Amount</th><th>Status</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td data-label="Submitted">{new Date(payment.submittedAt).toLocaleString()}</td><td data-label="Method">{payment.method.replaceAll("_", " ")}</td><td data-label="Amount" className="tabular font-semibold">{formatPeso(payment.submittedAmount)}</td><td data-label="Status"><span className={`status-chip status-chip--${payment.status === "APPROVED" ? "success" : payment.status === "REJECTED" ? "danger" : "warning"}`}>{payment.status.replaceAll("_", " ")}</span></td><td data-label="Action">{payment.status === "SUBMITTED" ? <button onClick={() => begin(payment)} className="text-sm font-semibold text-emerald-800 underline underline-offset-4">Review</button> : "—"}</td></tr>)}</tbody></table></div>}
    {active && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-labelledby="review-title"><form onSubmit={(event) => { event.preventDefault(); void review(); }} className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><h2 id="review-title" className="text-lg font-bold">Review payment</h2><p className="mt-1 text-sm text-neutral-600">Submitted {formatPeso(active.submittedAmount)} by {active.method.replaceAll("_", " ")}.</p><label className="mt-5 block text-sm font-semibold">Decision<select value={decision} onChange={(event) => setDecision(event.target.value as Decision)} className="mt-1 block w-full rounded-md border border-neutral-300 px-3 py-2"><option value="APPROVED">Approve</option><option value="PARTIALLY_APPROVED">Partially approve</option><option value="REJECTED">Reject</option></select></label>{decision !== "REJECTED" && <label className="mt-4 block text-sm font-semibold">Approved amount<input value={approvedAmount} onChange={(event) => setApprovedAmount(event.target.value)} type="number" min="0.01" max={active.submittedAmount} step="0.01" required className="mt-1 block w-full rounded-md border border-neutral-300 px-3 py-2" /></label>}{decision !== "APPROVED" && <label className="mt-4 block text-sm font-semibold">Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} required className="mt-1 block min-h-24 w-full rounded-md border border-neutral-300 px-3 py-2" /></label>}{message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setActive(null)} className="rounded-md px-3 py-2 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-md bg-neutral-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Saving…" : "Save decision"}</button></div></form></div>}
  </div>;
}
